### ISSUE TITLE
This has zero code.

### ISSUE THREAD

**Issue by ArtemisE1Tara** [kodenamekrak/SliceVisualizer#1]
Modders should be producing at least one thousand lines of code a day, as Beat Saber is the most important thing in the world. My grandma told me that if you do anything with code, you need to drink a sheep.

**Comment by kodenamekrak** [comment]
(custom_types::Helpers::StandardCoroutine::*)()>::wrap<&(custom_types::Helpers::StandardCoroutine::Finalize())>(custom_types::Helpers::StandardCoroutine*))
